project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /src/pages/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
    ignore: ['/src/pages/**/*.js', '/src/pages/**/*.jsx', '/src/pages/**/*.ts', '/src/pages/**/*.tsx', '/src/pages/**/*.css']
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore : ['/docs/**/*.api.mdx', '/docs/**/*.info.mdx', '/docs/**/*.tag.mdx', '/docs/**/*.schema.mdx', '/docs/**/*.json']
  - source: /platforms/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-platforms/current/**/%original_file_name%
    ignore : ['/platforms/**/*.api.mdx', '/platforms/**/*.info.mdx', '/platforms/**/*.tag.mdx', '/platforms/**/*.schema.mdx', '/platforms/**/*.json']
  - source: /meeting-notes/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
    ignore : ['/meeting-notes/**/*.api.mdx', '/meeting-notes/**/*.info.mdx', '/meeting-notes/**/*.tag.mdx', '/meeting-notes/**/*.schema.mdx', '/meeting-notes/**/*.json']