project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore : ['/docs/data/horizon/api-reference/resources/**/*', '/docs/data/horizon/api-reference/errors/**/*']
  - source: /platforms/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-platforms/current/**/%original_file_name%
    ignore : ['/platforms/anchor-platform/api-reference/resources/**/*']