# Crowdin credentials
project_id: '669532'
api_token_env: CROWDIN_PERSONAL_TOKEN

# Choose file structure in Crowdin
# e.g. true or false
preserve_hierarchy: true

# Files configuration
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore : ['**/*.api.mdx', '**/*.info.mdx', '**/*.tag.mdx', '**/*.schema.mdx', '**/*.json']
  # Stellar Disbursement Platform Docs Markdown files
  - source: /platforms/stellar-disbursement-platform/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-sdp/current/**/%original_file_name%
    ignore : ['**/*.api.mdx', '**/*.info.mdx', '**/*.tag.mdx', '**/*.schema.mdx', '**/*.json']
  # Anchor Platform Docs Markdown files
  - source: /platforms/anchor-platform/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-ap/current/**/%original_file_name%
    ignore : ['**/*.api.mdx', '**/*.info.mdx', '**/*.tag.mdx', '**/*.schema.mdx', '**/*.json']
  # Anchor Platform versioned docs
  - source: /ap_versioned_docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-ap/**/%original_file_name%
    ignore : ['**/*.api.mdx', '**/*.info.mdx', '**/*.tag.mdx', '**/*.schema.mdx', '**/*.json']
  # Meeting Notes Blog Markdown files
  - source: /meeting-notes/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
  # Pages Markdown files
  - source: /src/pages/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
    ignore: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.css']
    type: 'mdx_v2'
