allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: false
  core-js-pure: false
  postman-code-generators: true
  protobufjs: true
minimumReleaseAge: 4320
patchedDependencies:
  '@stoplight/json-schema-viewer@4.16.4': patches/@stoplight__json-schema-viewer.patch
