minimumReleaseAge: 4320
blockExoticSubdeps: true
strictDepBuilds: true

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  postman-code-generators: true
  protobufjs: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'detect-port@1.6.1'
  - 'semver@6.3.1'

patchedDependencies:
  '@stoplight/json-schema-viewer@4.16.4': patches/@stoplight__json-schema-viewer.patch
