// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebars;
