// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  horizon: [
    {
      type: 'category',
      label: 'Horizon',
      items: [
        {
          type: "autogenerated",
          dirName: "horizon",
        },
      ],
      collapsible: false,
    },
  ],
  anchor_platform: [
    {
      type: 'category',
      label: 'Anchor Platform',
      items: [
        {
          type: "autogenerated",
          dirName: "anchor-platform",
        },
      ],
    }
  ],
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      items: [
        {
          "type": "autogenerated",
          "dirName": "stellar-disbursement-platform"
        }
      ]
    }
  ]
}

module.exports = sidebars;
