// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: [{ type: "autogenerated", dirName: "introduction" }],
    },
    {
      type: "category",
      label: "Resources",
      items: require("./api/resources/sidebar"),
    },
    {
      type: "category",
      label: "Aggregations",
      items: [{ type: "autogenerated", dirName: "aggregations" }],
    },
    {
      type: "category",
      label: "Errors",
      items: [{ type: "autogenerated", dirName: "errors" }],
    },
  ],
};

module.exports = sidebars;
