// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    "index",
    {
      type: "category",
      label: "Where to Start",
      items: [
        "start/introduction",
        "start/stellar-stack",
        "start/list-of-operations",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/create-account",
        "tutorials/send-and-receive-payments",
        "tutorials/follow-received-payments",
        "tutorials/handling-errors",
        "tutorials/securing-projects",
      ],
    },
    {
      type: "category",
      label: "Issuing Assets",
      items: [
        "issuing-assets/index",
        "issuing-assets/anatomy-of-an-asset",
        "issuing-assets/how-to-issue-an-asset",
        "issuing-assets/publishing-asset-info",
        "issuing-assets/control-asset-access",
      ],
    },
    {
      type: "category",
      label: "Anchor Assets",
      items: [
        "anchoring-assets/index",
        {
          type: "category",
          label: "Enabling Cross-border Payments",
          link: {
            type: "doc",
            id: "anchoring-assets/enabling-cross-border-payments/index",
          },
          items: [
            "anchoring-assets/enabling-cross-border-payments/reference-implementations",
            "anchoring-assets/enabling-cross-border-payments/setting-up-test-server",
            "anchoring-assets/enabling-cross-border-payments/setting-up-production-server",
            "anchoring-assets/enabling-cross-border-payments/launch",
          ],
        },
        {
          type: "category",
          label: "Enable Deposits and Withdrawals",
          link: {
            type: "doc",
            id: "anchoring-assets/enabling-deposit-and-withdrawal/index",
          },
          items: [
            "anchoring-assets/enabling-deposit-and-withdrawal/reference-implementations",
            "anchoring-assets/enabling-deposit-and-withdrawal/setting-up-test-server",
            "anchoring-assets/enabling-deposit-and-withdrawal/setting-up-production-server",
            "anchoring-assets/enabling-deposit-and-withdrawal/launch",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Build Apps",
      items: [
        "building-apps/index",
        "building-apps/project-setup",
        "building-apps/key-management",
        "building-apps/basic-wallet",
        "building-apps/setup-custodial-account",
        "building-apps/xlm-payments",
        "building-apps/custom-assets",
        "building-apps/first-deposit",
        {
          type: "category",
          label: "Deposit and Withdraw From Anchors",
          link: { type: "doc", id: "building-apps/connect-to-anchors/index" },
          items: [
            "building-apps/connect-to-anchors/setup-for-anchored-assets",
            "building-apps/connect-to-anchors/deposit-anchored-assets",
            "building-apps/connect-to-anchors/withdraw-anchored-assets",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Run a Core Node",
      items: [
        "run-core-node/index",
        "run-core-node/prerequisites",
        "run-core-node/installation",
        "run-core-node/configuring",
        "run-core-node/publishing-history-archives",
        "run-core-node/running-node",
        "run-core-node/monitoring",
        "run-core-node/commands",
        "run-core-node/network-upgrades",
        "run-core-node/tier-1-orgs",
      ],
    },
    {
      type: "category",
      label: "Run an API Server",
      items: [
        "run-api-server/index",
        "run-api-server/prerequisites",
        "run-api-server/migrating",
        "run-api-server/installing",
        "run-api-server/configuring",
        "run-api-server/remote-core",
        "run-api-server/running",
        "run-api-server/ingestion",
        "run-api-server/monitoring",
        "run-api-server/scaling",
      ],
    },
    {
      type: "category",
      label: "Software and SDKs",
      items: ["software-and-sdks/index"],
    },
    {
      type: "category",
      label: "Glossary",
      items: [{ type: "autogenerated", dirName: "glossary" }],
    },
  ],
};

module.exports = sidebars;
