import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import sdpSidebar from './platforms/stellar-disbursement-platform/api-reference/sidebar'

const sidebars: SidebarsConfig = {
  anchor_platform: [
    {
      type: 'category',
      label: 'Anchor Platform',
      link: {
        type: 'doc',
        id: 'anchor-platform/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'anchor-platform',
        }
      ],
    },
  ],
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      link: {
        type: 'doc',
        id: 'stellar-disbursement-platform/README',
      },
      items: [
        'stellar-disbursement-platform/README',
        {
          type: 'category',
          label: "Admin Guide",
          link: {
            description: "All you need to know about setting up, running, and using the Anchor Platform.",
            type: 'generated-index',
            slug: '/stellar-disbursement-platform/admin-guide',
          },
          items: [
            { type: "autogenerated", dirName: "stellar-disbursement-platform/admin-guide" }
          ]
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsed: false,
          link: {
            description: 'View all Stellar Disbursement Platform API information.',
            type: 'generated-index',
            slug: '/stellar-disbursement-platform/api-reference',
          },
          items: [
            ...sdpSidebar.filter((item) => item.type === 'category'),
          ],
        },
      ],
    },
  ],
};

export default sidebars;
