// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'index',
    {
      'Fundamentals and Concepts': [{
        type: 'autogenerated',
        dirName: 'fundamentals-and-concepts',
      }]
    },
    {
      type: 'category',
      label: 'Basic Tutorials',
      link: {
        type: 'generated-index',
        title: 'Basic Tutorials',
        slug: '/category/basic-tutorials',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'tutorials',
      }]
    },
    {
      type: 'category',
      label: 'Issue Assets',
      link: {
        type: 'generated-index',
        title: 'Issue Assets',
        slug: '/category/issue-assets',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'issuing-assets',
      }]
    },
    {
      type: 'category',
      label: 'Build Applications',
      link: {
        type: 'generated-index',
        title: 'Build Applications',
        slug: '/category/build-applications',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'building-apps',
      }]
    },
    // {
    //   type: 'category',
    //   label: 'Run a Core Node',
    //   link: {
    //     type: 'doc',
    //     id: 'run-core-node/index'
    //   },
    //   // I can't (yet) figure out a way to autogenerate this without having
    //   // `overview` show up as an item
    //   items: [
    //     'run-core-node/prerequisites',
    //     'run-core-node/installation',
    //     'run-core-node/configuring',
    //     'run-core-node/publishing-history-archives',
    //     'run-core-node/running-node',
    //     'run-core-node/monitoring',
    //     'run-core-node/commands',
    //     'run-core-node/network-upgrades',
    //     'run-core-node/tier-1-orgs',
    //   ]
    // },
    {
      type: 'category',
      label: 'Encyclopedia',
      link: {
        type: 'generated-index',
        title: 'Encyclopedia',
        slug: '/category/encyclopedia',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'encyclopedia',
      }]
    },
    'glossary',
    'soroban',
  ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    }
  ],
};

module.exports = sidebars;
