import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import apSidebar from './platforms/anchor-platform/api-reference/sidebar'
import sdpSidebar from './platforms/stellar-disbursement-platform/api-reference/sidebar'

const sidebars: SidebarsConfig = {
  anchor_platform: [
    {
      type: 'category',
      label: 'Anchor Platform',
      items: [
        'anchor-platform/README',
        {
          type: 'category',
          label: "Admin Guide",
          link: {
            description: "All you need to know about setting up, running, and using the Anchor Platform.",
            type: 'generated-index',
            slug: '/anchor-platform/admin-guide',
          },
          items: [
            { type: "autogenerated", dirName: "anchor-platform/admin-guide" }
          ]
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsed: false,
          link: {
            description: 'View all Anchor Platform API information.',
            type: 'generated-index',
            slug: '/anchor-platform/api-reference',
          },
          items: [
            ...apSidebar.filter((item) => item.type === 'category'),
            {
              type: 'category',
              label: "JSON-RPC API",
              link: {
                description: "Interact with your Anchor Platform instance through the use of lightweight, easy-to-use RPC requests.",
                type: 'generated-index',
                slug: '/anchor-platform/api-reference/rpc',
              },
              items: [
                { type: "autogenerated", dirName: "anchor-platform/api-reference/rpc" }
              ]
            },
          ],
        }
      ],
    },
  ],
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      items: [
        'stellar-disbursement-platform/README',
        {
          type: 'category',
          label: "Admin Guide",
          link: {
            description: "All you need to know about setting up, running, and using the Anchor Platform.",
            type: 'generated-index',
            slug: '/stellar-disbursement-platform/admin-guide',
          },
          items: [
            { type: "autogenerated", dirName: "stellar-disbursement-platform/admin-guide" }
          ]
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsed: false,
          link: {
            description: 'View all Stellar Disbursement Platform API information.',
            type: 'generated-index',
            slug: '/stellar-disbursement-platform/api-reference',
          },
          items: [
            ...sdpSidebar.filter((item) => item.type === 'category'),
          ],
        },
      ],
    },
  ],
};

export default sidebars;
