// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  overview: [
    'README',
    'requirements',
    { type: 'html', value: '<small>Data Availability</small>', defaultStyle: true, className: 'networkMenuHtmlItem'},
    { type: 'ref', id: 'soroban-rpc/README', label: 'Soroban RPC'},
    { type: 'ref', id: 'hubble/README', label: 'Hubble'},
    { type: 'ref', id: 'horizon/README', label: 'Horizon'},
    { type: 'html', value: '<small>Platforms</small>', defaultStyle: true, className: 'networkMenuHtmlItem'},
    { type: 'ref', id: 'anchor-platform/README', label: 'Anchor Platform'},
    { type: 'ref', id: 'stellar-disbursement-platform/README', label: 'Stellar Disbursement Platform'},
    { type: 'html', value: '<small>Network Infrastructure</small>', defaultStyle: true, className: 'networkMenuHtmlItem'},
    { type: 'ref', id: 'core-node/README', label: 'Core Validator Node'},
  ],
  horizon: [
    {
      type: 'category',
      label: 'Horizon',
      items: [
        {
          type: "autogenerated",
          dirName: "horizon",
        },
      ],
      collapsible: false,
    },
  ],
  hubble: [
    {
      type: 'category',
      label: 'Hubble',
      items: [
        {
          type: "autogenerated",
          dirName: "hubble",
        },
      ],
      collapsible: false,
    },
  ],
  anchor_platform: [
    {
      type: 'category',
      label: 'Anchor Platform',
      items: [
        {
          type: "autogenerated",
          dirName: "anchor-platform",
        },
      ],
    },
  ],
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      items: [
        {
          type: "autogenerated",
          dirName: "stellar-disbursement-platform",
        },
      ],
    },
  ],
  soroban_rpc: [
    {
      type: "category",
      label: "Soroban RPC",
      items: [
        {
          type: 'autogenerated',
          dirName: 'soroban-rpc',
        },
      ],
    },
  ],
  core_node: [
    {
      type: 'category',
      label: 'Core Node',
      items: [
        {
          type: 'autogenerated',
          dirName: 'core-node',
        },
      ],
    },
  ],
}

module.exports = sidebars;
