// @ts-check
import horizonSidebar from './network/horizon/api-reference/sidebar'

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  horizon: [
    {
      type: 'category',
      label: 'Horizon',
      link: {type: 'doc', id: 'horizon/README'},
      items: [
        'horizon/README',
        {
          type: 'category',
          label: 'Admin Guide',
          link: {
            type: 'doc', id: 'horizon/admin-guide/README'
          },
          items: [
            {type: 'autogenerated', dirName: 'horizon/admin-guide'}
          ]
        },
        {
          type: 'category',
          label: 'API Reference',
          link: {
            type: 'doc', id: 'horizon/api-reference/README',
          },
          items: [
            horizonSidebar,
          ]
        }
      ],
      collapsible: false,
    },
  ],
  hubble: [
    {
      type: 'category',
      label: 'Hubble',
      items: [
        {
          type: "autogenerated",
          dirName: "hubble",
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'link',
              label: 'Data Lineage',
              href: 'http://www.stellar-dbt-docs.com/#!/overview',
            },
          ],
        },
      ],
      collapsible: false,
    },
  ],
  anchor_platform: [
    {
      type: 'category',
      label: 'Anchor Platform',
      items: [
        {
          type: "autogenerated",
          dirName: "anchor-platform",
        },
      ],
    },
  ],
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      items: [
        {
          type: "autogenerated",
          dirName: "stellar-disbursement-platform",
        },
      ],
    },
  ],
  soroban_rpc: [
    {
      type: "category",
      label: "Soroban RPC",
      items: [
        {
          type: 'autogenerated',
          dirName: 'soroban-rpc',
        },
      ],
    },
  ],
  core_node: [
    {
      type: 'category',
      label: 'Core Node',
      items: [
        {
          type: 'autogenerated',
          dirName: 'core-node',
        },
      ],
    },
  ],
}

module.exports = sidebars;
