import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import platformSidebar from './platforms/anchor-platform/api-reference/platform/sidebar'
// import callbacksSidebar from './platforms/anchor-platform/api-reference/callbacks/sidebar'
// import custodySidebar from './platforms/anchor-platform/api-reference/custody/sidebar'
import sdpSidebar from './platforms/stellar-disbursement-platform/api-reference/sidebar'
import zSidebar from './platforms/anchor-platform/api-reference/zesty/sidebar'

platformSidebar.push({
  type: 'category',
  label: "JSON-RPC API",
  link: {
    description: "RPC Stuff goes here?",
    type: 'generated-index',
    slug: '/anchor-platform/api-reference/platform/rpc',
  },
  items: [
    { type: "autogenerated", dirName: "anchor-platform/api-reference/platform/rpc" }
  ]
})

const sidebars: SidebarsConfig = {
  anchor_platform: [
    {
      type: 'category',
      label: 'Anchor Platform',
      items: [
        'anchor-platform/README',
        {
          type: 'category',
          label: "Admin Guide",
          link: {
            description: "All you need to know about setting up, running, and using the Anchor Platform.",
            type: 'generated-index',
            slug: '/anchor-platform/admin-guide',
          },
          items: [
            { type: "autogenerated", dirName: "anchor-platform/admin-guide" }
          ]
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsed: false,
          link: {
            description: 'View all Anchor Platform API information.',
            type: 'generated-index',
            slug: '/anchor-platform/api-reference',
          },
          items: [
            {
              type: 'category',
              label: "Platform Server",
              link: {
                description: "The platform server is an internal component. It should be hosted in a private network and should not be accessible from the Internet. This server enables the business to fetch and update the state of transactions using its API.",
                type: 'generated-index',
                slug: '/anchor-platform/api-reference/platform',
              },
              items: [
                ...platformSidebar
              ]
            },
            {
              type: 'category',
              label: "Callbacks Server",
              link: {
                description: "The Anchor Platform provides several callback functionalities for your business server.",
                type: 'generated-index',
                slug: '/anchor-platform/api-reference/callbacks',
              },
              items: [
                { type: "autogenerated", dirName: "anchor-platform/api-reference/callbacks" }
              ]
            },
            {
              type: 'category',
              label: "Custody Server",
              link: {
                description: "The Custody Server provides a set of endpoints to interact with custody services, such as Fireblocks.",
                type: 'generated-index',
                slug: '/anchor-platform/api-reference/custody',
              },
              items: [
                { type: "autogenerated", dirName: "anchor-platform/api-reference/custody" }
              ]
            },
          ],
        },
        ...zSidebar
      ],
    },
  ],
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      items: [
        'stellar-disbursement-platform/README',
        {
          type: 'category',
          label: "Admin Guide",
          link: {
            description: "All you need to know about setting up, running, and using the Anchor Platform.",
            type: 'generated-index',
            slug: '/stellar-disbursement-platform/admin-guide',
          },
          items: [
            { type: "autogenerated", dirName: "stellar-disbursement-platform/admin-guide" }
          ]
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsed: false,
          link: {
            description: 'View all Stellar Disbursement Platform API information.',
            type: 'generated-index',
            slug: '/stellar-disbursement-platform/api-reference',
          },
          items: [
            ...sdpSidebar.filter((item) => item.type === 'category'),
          ],
        },
      ],
    },
  ],
};

export default sidebars;
