// Client module for the markdown-source feature (follow-up to PR #2289,
// issue #2643): show the "Open Markdown" button on API reference pages.
//
// docusaurus-markdown-source-plugin injects its actions dropdown into
// `article .markdown header`, which exists on regular doc pages but not on
// the operation pages generated by docusaurus-plugin-openapi-docs (they
// render an `h1.openapi__heading` and no `<header>`), so the button never
// appears there. This module injects the SAME dropdown component next to
// that heading, only on operation pages, and only when the plugin hasn't
// already injected one — regular pages (including prose pages that live
// under /api-reference/ routes) are left entirely to the plugin.

import React from 'react';
import { createRoot } from 'react-dom/client';
import MarkdownActionsDropdown from 'docusaurus-markdown-source-plugin/components/MarkdownActionsDropdown';

let activeObserver = null;
let activeRoot = null;
let activeContainer = null;

function cleanup() {
  if (activeObserver) {
    activeObserver.disconnect();
    activeObserver = null;
  }
  if (activeRoot) {
    activeRoot.unmount();
    activeRoot = null;
  }
  if (activeContainer) {
    activeContainer.remove();
    activeContainer = null;
  }
}

function inject() {
  // Operation pages only; anything else belongs to the plugin's own injection.
  const heading = document.querySelector('h1.openapi__heading');
  if (!heading) return false;

  // Never double up — neither with the plugin's dropdown nor with our own.
  if (document.querySelector('.markdown-actions-container')) return true;

  const container = document.createElement('div');
  container.className = 'markdown-actions-container';
  heading.insertAdjacentElement('afterend', container);
  activeContainer = container;

  activeRoot = createRoot(container);
  activeRoot.render(React.createElement(MarkdownActionsDropdown));
  return true;
}

export function onRouteDidUpdate({ location }) {
  cleanup();
  if (!location.pathname.includes('/api-reference/')) return;

  inject();

  // The operation content hydrates client-side and Docusaurus swaps the DOM
  // asynchronously on navigation, so keep watching (like the plugin does) and
  // re-inject if the heading appears late or our container is swapped away.
  activeObserver = new MutationObserver(() => {
    if (!document.querySelector('.markdown-actions-container')) {
      if (activeRoot) {
        activeRoot.unmount();
        activeRoot = null;
      }
      activeContainer = null;
      inject();
    }
  });
  activeObserver.observe(document.body, { childList: true, subtree: true });
}
