name: Build docs
description: "Links necessary external dependencies (such as stellar cli) and builds docs"
inputs:
  cli-ref:
    required: false
    default: ''
    description: "Stellar-cli ref to build against. If empty, will use latest cli version"
  docs-repo:
    required: true
    default: ${{ github.action_repository }}
    description: "Stellar-docs repository"
runs:
  using: "composite"
  steps:
    - run: echo $DOCS_REPO
      shell: bash
      env:
        DOCS_REPO: ${{ inputs.docs-repo }}

    - name: Checkout App Repo
      uses: actions/checkout@v4
      with:
        repository: $DOCS_REPO
      env:
        DOCS_REPO: ${{ inputs.docs-repo }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Install App Dependencies
      run: yarn --prefer-offline
      shell: bash

    - name: Copy Files From Stellar CLI
      run: yarn stellar-cli:build -- --cli-ref='${{ inputs.cli-ref }}'
      shell: bash

    - name: Build app
      run: yarn build
      shell: bash


