import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    anchor_platform: [
        {
            type: 'category',
            label: 'Anchor Platform',
            link: {
                type: 'doc',
                id: 'README',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: '.',
                }
            ],
        },
    ],
}

export default sidebars;
