import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  anchor_platform: [
    {
      type: "category",
      label: "Anchor Platform",
      link: {
        type: "doc",
        id: "README",
      },
      items: [
        "README",
        {
          type: "category",
          label: "Admin Guide",
          link: {
            description:
              "All you need to know about setting up, running, and using the Anchor Platform.",
            type: "generated-index",
            slug: "/admin-guide",
          },
          items: [{ type: "autogenerated", dirName: "admin-guide" }],
        },
        {
          type: "category",
          label: "SEP Guides",
          link: {
            description:
              "Guides for implementing Stellar Ecosystem Proposals (SEPs) with the Anchor Platform.",
            type: "generated-index",
            slug: "/sep-guide",
          },
          items: [{ type: "autogenerated", dirName: "sep-guide" }],
        },
        {
          type: "category",
          label: "API Reference",
          collapsed: false,
          link: {
            description:
              "View all Anchor Platform API information.",
            type: "generated-index",
            slug: "/api-reference",
          },
          items: [{ type: "autogenerated", dirName: "api-reference" }],
        },
      ],
    },
  ],
};

export default sidebars;
