import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    anchor_platform: [
        {
            type: 'category',
            label: 'Anchor Platform',
            link: {
                type: 'doc',
                id: 'platforms/anchor-platform/README',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'platforms/anchor-platform',
                }
            ],
        },
    ],
}

export default sidebars;
