import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import sdpSidebar from "../docs/platforms/stellar-disbursement-platform/api-reference/sidebar";

const sidebars: SidebarsConfig = {
  stellar_disbursement_platform: [
    {
      type: "category",
      label: "Stellar Disbursement Platform",
      link: {
        type: "doc",
        id: "platforms/stellar-disbursement-platform/README",
      },
      items: [
        "platforms/stellar-disbursement-platform/README",
        {
          type: "category",
          label: "Admin Guide",
          collapsed: false,
          link: {
            description:
              "All you need to know about setting up, running, and using the Stellar Disbursement Platform.",
            type: "generated-index",
            slug: "platforms/stellar-disbursement-platform/admin-guide",
          },
          items: [{ type: "autogenerated", dirName: "platforms/stellar-disbursement-platform/admin-guide" }],
        },
        {
          type: "category",
          label: "API Reference",
          collapsed: true,
          link: {
            description:
              "View all Stellar Disbursement Platform API information.",
            type: "generated-index",
            slug: "platforms/stellar-disbursement-platform/api-reference",
          },
          items: [...sdpSidebar.filter((item) => item.type === "category")],
        },
      ],
    },
  ],
};

export default sidebars;
