import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  build: [
    {
      type: 'autogenerated',
      dirName: 'build',
    },
  ],
  learn: [
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
  ],
  tokens: [
    {
      type: 'autogenerated',
      dirName: 'tokens',
    },
  ],
  data_overview: [
    'data/README',
    { type: 'ref', id: 'data/analytics/README', label: 'Analytics'},
    { type: 'ref', id: 'data/apis/README', label: 'API'},
    { type: 'ref', id: 'data/indexing/README', label: 'Indexing'},
    { type: 'ref', id: 'data/oracles/README', label: 'Oracles'},
  ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    },
    { type: 'html', value: '<small>SDF Platforms</small>', defaultStyle: true, className: 'networkMenuHtmlItem'},
    { type: 'link', href: '/platforms/anchor-platform', label: 'Anchor Platform'},
    { type: 'link', href: '/platforms/stellar-disbursement-platform', label: 'Stellar Disbursement Platform'},
  ],
  networks: [
    {
      type: 'autogenerated',
      dirName: 'networks',
    },
  ],
  validators: [
    {
      type: 'autogenerated',
      dirName: 'validators',
    },
  ],
  horizon: [
    {
      type: 'category',
      label: 'Horizon',
      items: [
        {
          type: "autogenerated",
          dirName: "data/apis/horizon",
        },
      ],
      collapsible: false,
    },
  ],
  hubble: [
    {
      type: 'category',
      label: 'Hubble',
      items: [
        {
          type: "autogenerated",
          dirName: "data/analytics/hubble",
        },
      ],
      collapsible: false,
    },
  ],
  galexie: [
    {
      type: 'category',
      label: 'Galexie',
      items: [
        {
          type: "autogenerated",
          dirName: "data/indexing/build-your-own/galexie",
        },
      ],
      collapsible: false,
    },
  ],
  soroban_rpc: [
    {
      type: "category",
      label: "Stellar RPC",
      items: [
        {
          type: 'autogenerated',
          dirName: 'data/apis/rpc',
        },
      ],
      collapsible: false,
    },
  ],
  data_indexers: [
    {
      type: 'category',
      label: 'Data Indexers',
      items: [
        {
          type: "autogenerated",
          dirName: "data/indexing/data-indexers",
        },
      ],
      collapsible: false,
    },
  ],
  analytics: [
    {
      type: 'category',
      label: 'Analytics',
      items: [
        {
          type: "autogenerated",
          dirName: "data/analytics",
        },
      ],
      collapsible: false,
    },
  ],
  apis: [
    {
      type: 'category',
      label: 'APIs',
      items: [
        {
          type: "autogenerated",
          dirName: "data/apis",
        },
      ],
      collapsible: false,
    },
  ],
  indexing: [
    {
      type: 'category',
      label: 'Indexing',
      items: [
        {
          type: "autogenerated",
          dirName: "data/indexing",
        },
      ],
      collapsible: false,
    },
  ],
  oracles: [
    {
      type: 'category',
      label: 'Oracles',
      items: [
        {
          type: "autogenerated",
          dirName: "data/oracles",
        },
      ],
      collapsible: false,
    },
  ],
};

export default sidebars;
