import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  build: [
    {
      type: 'autogenerated',
      dirName: 'build',
    },
  ],
  learn: [
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
  ],
  tokens: [
    {
      type: 'autogenerated',
      dirName: 'tokens',
    },
  ],
  data: [
    {
      type: 'autogenerated',
      dirName: 'data',
    }
  ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    },
    { type: 'html', value: '<small>SDF Platforms</small>', defaultStyle: true, className: 'networkMenuHtmlItem'},
    { type: 'link', href: '/platforms/anchor-platform', label: 'Anchor Platform'},
    { type: 'link', href: '/platforms/stellar-disbursement-platform', label: 'Stellar Disbursement Platform'},
  ],
  networks: [
    {
      type: 'autogenerated',
      dirName: 'networks',
    },
  ],
  validators: [
    {
      type: 'autogenerated',
      dirName: 'validators',
    },
  ],
};

export default sidebars;
