// @ts-check
/**
 * Post-build step for the markdown-source feature (follow-up to PR #2289,
 * issue #2643): generate complete `.md` twins for API reference pages.
 *
 * The docusaurus-markdown-source-plugin builds each page's `.md` twin from the
 * page's static content. That works for prose pages, but API reference pages
 * (generated by docusaurus-plugin-openapi-docs from the bundled OpenAPI specs)
 * render their operation content — parameters, request/response schemas,
 * examples — client-side, so their twins come out near-empty: just the
 * one-line operation description (~39 tokens vs ~14k tokens of rendered HTML).
 *
 * This script rebuilds those twins from the operation data itself. Every
 * `docs/**\/api-reference/**\/*.api.mdx` source file carries the complete,
 * dereferenced operation object (the exact data the page renders) in its
 * `api:` frontmatter field, zlib-compressed and base64-encoded by the openapi
 * plugin. We decode it and emit clean markdown — method + path, auth,
 * parameters, request body, response schemas, and examples — over the
 * near-empty twin at the matching `build/**\/api-reference/**\/<id>.md` path.
 *
 * Like scripts/rewrite_md_links.mjs (which runs after this in `postbuild` and
 * normalizes any intra-doc links), this is output-only: it writes ONLY
 * `build/**\/api-reference/**\/*.md`, never touches HTML or repo sources, and
 * is idempotent (deterministic output; unchanged files are not rewritten).
 */

import { globSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { inflateSync } from 'node:zlib';
import { dirname, join, relative } from 'node:path';

const DOCS_DIR = 'docs';
const BUILD_DIR = 'build';
const MAX_DEPTH = 12; // schema nesting cap; blobs are acyclic but can run deep
const MAX_EXAMPLE_CHARS = 20000; // skip pathological examples, keep real ones

// ---------------------------------------------------------------------------
// Frontmatter + operation blob
// ---------------------------------------------------------------------------

/** Pull the fields we need out of an .api.mdx frontmatter block. */
function parseFrontmatter(src) {
  const fm = src.match(/^---\n([\s\S]*?)\n---/);
  if (!fm) return null;
  const get = (key) => {
    const m = fm[1].match(new RegExp(`^${key}: (.+)$`, 'm'));
    if (!m) return null;
    let v = m[1].trim();
    if (v.startsWith('"') && v.endsWith('"')) {
      v = v.slice(1, -1).replace(/\\"/g, '"');
    }
    return v;
  };
  return { id: get('id'), title: get('title'), api: get('api') };
}

/** Decode the `api:` frontmatter value into the operation object. */
function decodeOperation(apiValue) {
  if (apiValue.startsWith('{')) return JSON.parse(apiValue); // uncompressed
  return JSON.parse(inflateSync(Buffer.from(apiValue, 'base64')).toString('utf8'));
}

// ---------------------------------------------------------------------------
// Schema rendering — nested bullet tree
// ---------------------------------------------------------------------------

/** Human-readable type for a schema node, e.g. "array of object", "string (uuid)". */
function typeLabel(schema) {
  if (!schema || typeof schema !== 'object') return 'any';
  if (schema.oneOf) return 'one of';
  if (schema.anyOf) return 'any of';
  if (schema.allOf) return 'object';
  let base = schema.type;
  if (!base) base = schema.properties ? 'object' : schema.items ? 'array' : 'any';
  if (base === 'array') return `array of ${typeLabel(schema.items)}`;
  let label = base;
  if (schema.format) label += ` (${schema.format})`;
  if (schema.nullable) label += ', nullable';
  return label;
}

/** Collapse a (possibly multi-line, markdown-ish) description onto one line. */
function inlineText(text) {
  if (!text) return '';
  return String(text).replace(/\s*\n\s*/g, ' ').trim();
}

/** Merge the object members of an allOf into one view; keep the rest as-is. */
function mergeAllOf(schema) {
  const merged = { type: 'object', properties: {}, required: [] };
  const leftovers = [];
  for (const member of schema.allOf) {
    if (member && typeof member === 'object' && (member.properties || member.type === 'object')) {
      Object.assign(merged.properties, member.properties ?? {});
      merged.required.push(...(member.required ?? []));
      if (member.description && !merged.description) merged.description = member.description;
    } else if (member) {
      leftovers.push(member);
    }
  }
  return { merged, leftovers };
}

/** One bullet line for a named schema node. */
function propertyLine(name, schema, required) {
  const parts = [`\`${name}\``, '—', typeLabel(schema)];
  if (required) parts.push('(required)');
  if (schema?.deprecated) parts.push('(deprecated)');
  const desc = inlineText(schema?.description);
  if (desc) parts.push('—', desc);
  return parts.join(' ');
}

/** Trailing detail bullets (enum/default/example) for a schema node. */
function detailLines(schema, pad, lines) {
  if (schema.enum) {
    lines.push(`${pad}Possible values: ${schema.enum.map((v) => `\`${v}\``).join(', ')}.`);
  }
  if (schema.default !== undefined) {
    lines.push(`${pad}Default: \`${JSON.stringify(schema.default)}\`.`);
  }
}

/**
 * Render a schema's CHILDREN (properties / variants / items) as indented
 * bullets. The node's own line is the caller's responsibility.
 */
function renderChildren(schema, depth, lines) {
  if (!schema || typeof schema !== 'object' || depth > MAX_DEPTH) {
    if (depth > MAX_DEPTH) lines.push(`${'  '.repeat(depth)}- … (nesting truncated)`);
    return;
  }
  const pad = '  '.repeat(depth);

  if (schema.allOf) {
    const { merged, leftovers } = mergeAllOf(schema);
    renderChildren(merged, depth, lines);
    for (const leftover of leftovers) renderChildren(leftover, depth, lines);
    return;
  }

  for (const key of ['oneOf', 'anyOf']) {
    if (schema[key]) {
      schema[key].forEach((variant, i) => {
        const name = variant?.title ?? `variant ${i + 1}`;
        lines.push(`${pad}- ${key === 'oneOf' ? 'One of' : 'Any of'}: **${name}** — ${typeLabel(variant)}`);
        renderChildren(variant, depth + 1, lines);
      });
      return;
    }
  }

  if (schema.type === 'array' || schema.items) {
    renderChildren(schema.items, depth, lines);
    return;
  }

  const required = new Set(schema.required ?? []);
  for (const [name, child] of Object.entries(schema.properties ?? {})) {
    lines.push(`${pad}- ${propertyLine(name, child, required.has(name))}`);
    detailLines(child, `${pad}  `, lines);
    renderChildren(child, depth + 1, lines);
  }
  if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    lines.push(`${pad}- (additional properties) — ${typeLabel(schema.additionalProperties)}`);
    renderChildren(schema.additionalProperties, depth + 1, lines);
  }
}

/** Render a full schema (top line + children) as markdown lines. */
function renderSchema(schema, lines) {
  if (!schema || typeof schema !== 'object') return;
  const topDesc = inlineText(schema.description);
  const isLeaf = !schema.properties && !schema.items && !schema.allOf && !schema.oneOf && !schema.anyOf;
  if (isLeaf || schema.oneOf || schema.anyOf) {
    lines.push(`Schema: ${typeLabel(schema)}${topDesc ? ` — ${topDesc}` : ''}`);
    detailLines(schema, '', lines);
  } else if (topDesc) {
    lines.push(topDesc);
  }
  renderChildren(schema, 0, lines);
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

function fencedJson(value, lines) {
  const json = JSON.stringify(value, null, 2);
  if (json === undefined || json.length > MAX_EXAMPLE_CHARS) return;
  lines.push('```json', json, '```');
}

/** Examples attached to a media-type object ({example} or {examples: {..}}). */
function renderExamples(media, lines) {
  if (media.example !== undefined) {
    lines.push('', 'Example:', '');
    fencedJson(media.example, lines);
    return;
  }
  const entries = Object.entries(media.examples ?? {});
  for (const [name, entry] of entries) {
    lines.push('', entries.length > 1 ? `Example (${name}):` : 'Example:', '');
    fencedJson(entry?.value !== undefined ? entry.value : entry, lines);
  }
}

function renderParameters(parameters, lines) {
  const groups = new Map([['path', []], ['query', []], ['header', []], ['cookie', []]]);
  for (const param of parameters) groups.get(param.in)?.push(param);
  lines.push('', '## Parameters');
  for (const [location, params] of groups) {
    if (!params.length) continue;
    lines.push('', `### ${location[0].toUpperCase()}${location.slice(1)} parameters`, '');
    lines.push('| Name | Type | Required | Description |', '| --- | --- | --- | --- |');
    for (const param of params) {
      let desc = inlineText(param.description).replace(/\|/g, '\\|');
      if (param.schema?.enum) {
        desc += `${desc ? ' ' : ''}Possible values: ${param.schema.enum.map((v) => `\`${v}\``).join(', ')}.`;
      }
      if (param.schema?.default !== undefined) {
        desc += ` Default: \`${JSON.stringify(param.schema.default)}\`.`;
      }
      lines.push(`| \`${param.name}\` | ${typeLabel(param.schema)} | ${param.required ? 'yes' : 'no'} | ${desc} |`);
    }
  }
}

function renderRequestBody(op, lines) {
  const body = op.requestBody;
  lines.push('', `## Request body${body.required ? ' (required)' : ''}`);
  for (const [contentType, media] of Object.entries(body.content ?? {})) {
    lines.push('', `Content type: \`${contentType}\``, '');
    if (media.schema) renderSchema(media.schema, lines);
    if (media.example !== undefined || media.examples) {
      renderExamples(media, lines);
    } else if (media.schema?.example !== undefined) {
      lines.push('', 'Example:', '');
      fencedJson(media.schema.example, lines);
    } else if (op.jsonRequestBodyExample != null) {
      lines.push('', 'Example:', '');
      fencedJson(op.jsonRequestBodyExample, lines);
    }
  }
}

function renderResponses(responses, lines) {
  lines.push('', '## Responses');
  for (const [status, response] of Object.entries(responses)) {
    lines.push('', `### ${status}`, '');
    const desc = inlineText(response.description);
    if (desc) lines.push(desc, '');
    for (const [contentType, media] of Object.entries(response.content ?? {})) {
      lines.push(`Content type: \`${contentType}\``, '');
      if (media.schema) renderSchema(media.schema, lines);
      renderExamples(media, lines);
    }
  }
}

/** Render one operation object as a complete markdown page. */
function renderOperation(op, title) {
  const lines = [`# ${title}`, '', `\`${(op.method ?? '').toUpperCase()} ${op.path}\``];

  const servers = (op.servers ?? []).filter((server) => server.url);
  if (servers.length) {
    lines.push('', ...servers.map(
      (server) => `- Base URL: \`${server.url}\`${server.description ? ` (${server.description})` : ''}`,
    ));
  }
  if (op.description) lines.push('', op.description.trim());
  if (op['x-supports-streaming']) {
    lines.push('', 'This endpoint supports [streaming](https://developers.stellar.org/docs/data/apis/horizon/api-reference/structure/streaming.md) via Server-Sent Events.');
  }
  const securityNames = (op.security ?? []).flatMap((requirement) => Object.keys(requirement));
  if (securityNames.length) {
    lines.push('', `Authentication: ${securityNames.map((name) => `\`${name}\``).join(' or ')}.`);
  }

  if (op.parameters?.length) renderParameters(op.parameters, lines);
  if (op.requestBody) renderRequestBody(op, lines);
  if (op.responses) renderResponses(op.responses, lines);

  const codeSamples = op['x-codeSamples'] ?? [];
  if (codeSamples.length) {
    lines.push('', '## Code samples');
    for (const sample of codeSamples) {
      lines.push('', `\`\`\`${(sample.lang ?? '').toLowerCase()}`, sample.source ?? '', '```');
    }
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  if (!existsSync(BUILD_DIR)) {
    console.warn(`[generate-api-markdown] "${BUILD_DIR}/" not found — skipping.`);
    return;
  }

  const sources = globSync(`${DOCS_DIR}/**/*.api.mdx`)
    .filter((p) => p.includes('/api-reference/'))
    .sort();

  let written = 0;
  let unchanged = 0;
  let skipped = 0;

  for (const source of sources) {
    const fm = parseFrontmatter(readFileSync(source, 'utf8'));
    if (!fm?.id || !fm.api) {
      console.warn(`[generate-api-markdown] no id/api frontmatter in ${source} — skipping.`);
      skipped++;
      continue;
    }

    // docs/<section>/<name>.api.mdx -> build/docs/<section>/<id>.md
    const twin = join(BUILD_DIR, DOCS_DIR, relative(DOCS_DIR, dirname(source)), `${fm.id}.md`);
    if (!existsSync(dirname(twin))) {
      console.warn(`[generate-api-markdown] no built output dir for ${source} — skipping.`);
      skipped++;
      continue;
    }

    let markdown;
    try {
      markdown = renderOperation(decodeOperation(fm.api), fm.title ?? fm.id);
    } catch (error) {
      console.warn(`[generate-api-markdown] failed to decode ${source}: ${error.message} — skipping.`);
      skipped++;
      continue;
    }

    if (existsSync(twin) && readFileSync(twin, 'utf8') === markdown) {
      unchanged++;
      continue;
    }
    writeFileSync(twin, markdown);
    written++;
  }

  console.log(
    `[generate-api-markdown] Wrote ${written} API reference twin(s) (${unchanged} already current, ${skipped} skipped) from ${sources.length} operation source(s).`,
  );
}

main();
