openapi: 3.0.0
info:
  version: "2.0.0"
  title: Event Schemas
  description: |
    This document specifies the schemas used for Events in Stellar Anchor Platform project.
    
    There are currently two types of Events: `QuoteEvent` and `TransactionEvent`. When events occur (quote_created, transaction_created, etc...), the events are published by the Anchor Platform to a queue (Kafka, SQS, ect...) for the Anchor to consume and process.
    
    This differs from the Callbacks API, which defines requests made while the Platform is processing a request from a client application.
tags:
  - name: "Event Schemas"
    description: "Event Schemas for events that are published to a queue for the Anchor to consume."
paths: { }
components:
  schemas:
    Event:
      $ref: './schemas.yml#/components/schemas/Event'
