openapi: 3.0.0
info:
  version: "2.0.0"
  title: Examples
  description: |
    This document specifies the examples used for all APIs.
tags:
  - name: "Examples"
    description: "Examples"
paths: { }
components:
  examples:
    SuccessKYC:
      summary: The case when a customer has been successfully KYC'd and approved
      value: {
        "id": "d1ce2f48-3ff1-495d-9240-7a50d806cfed",
        "status": "ACCEPTED",
        "provided_fields": {
          "first_name": {
            "description": "The customer's first name",
            "type": "string",
            "status": "ACCEPTED"
          },
          "last_name": {
            "description": "The customer's last name",
            "type": "string",
            "status": "ACCEPTED"
          },
          "email_address": {
            "description": "The customer's email address",
            "type": "string",
            "status": "ACCEPTED"
          }
        }
      }
